#!/bin/sh
QEMU_FLAGS="-display gtk,zoom-to-fit=on -enable-kvm -m 2048"

if [ ! -f drive.img ]; then
	DIR=$(pwd)
	ISO=$(mktemp)
	mkdir mnt
	wget -O $ISO "https://templeos.org/Downloads/TempleOS.ISO"
	cd $(mktemp -d)
	wget "https://templeos.org/Downloads/Linux/TOSZ"
	wget "https://templeos.org/Downloads/Linux/TOSZ.CPP"
	wget "https://templeos.org/Downloads/Linux/make_tosz"
	source ./make_tosz
	cp TOSZ $DIR
	cd $DIR
	qemu-img create drive.img 1G
	qemu-system-x86_64 $QEMU_FLAGS -cdrom $ISO -drive file=drive.img,format=raw -boot d
	exit
fi

rm -rf mnt/*
sudo cp -rf Root/* mnt
sync mnt
sudo umount mnt/
rm -rf Root
qemu-system-x86_64 $QEMU_FLAGS -drive file=drive.img,format=raw
sudo mount -o loop,offset=32256,rw,uid=$(id -u),gid=$(id -g) drive.img mnt/
cp -rf mnt Root
sync Root
