#!/bin/sh

sync
sudo umount mnt/ 2> /dev/null
mkdir mnt 2> /dev/null
sudo mount -o loop,offset=32256,rw,uid=$(id -u),gid=$(id -g) "drive.img" mnt/

case $1 in
    "from")
        rsync -avz --delete mnt/Home .
    ;;
    "to")
        rsync -avz --delete Home mnt/
    ;;
	*) echo "to|from" ;;
esac
